name: luxury_hotel
description: A modern and elegant luxury hotel booking application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  image_cropper_platform_interface: ^7.0.0
  logger: ^2.5.0
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  http: ^1.2.0
  excel: ^4.0.6
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  connectivity_plus: ^6.1.0
  dio: ^5.4.0
  intl: ^0.20.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/rooms/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
